### ISSUE TITLE
Cockpit service inactive/dead

### ISSUE THREAD

**Issue by jeremygabillet** [YunoHost-Apps/cockpit_ynh#20]
### Describe the bug

The cockpit service seems to die a few minutes after rebooting the service. However when I connect to the app on my server, it seems to work normally, except for the history since it was dead.

### Context

- Hardware: Old laptop
- YunoHost version: 11.2.3
- I have access to my server: Through SSH & through the webadmin & direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: 188~ynh2

### Steps to reproduce

Run the cockpit service. Wait a few minutes (can't say exactly) and check the status.

### Expected behavior

I expect cockpit to remain active.

### Logs

So this bugs me but I can't seem to find any trace of what went wrong in the logs : https://paste.yunohost.org/mayoqulisa
Maybe there's somewhere else I could find more detailed logs ?

Thank you for you help !

**Comment by orhtej2** [comment]
I got that misconception as well, it's not a bug.
`systemd` spawns a new instance on each connection to `cockpit.socket` and recycles old instances as needed. The app should still remain perfectly usable as the service will be revived when necessary.
